### ISSUE TITLE
干员信息部分的消息出不来

### ISSUE THREAD

**Issue by ENE4546** [NumberSir/nonebot_plugin_arktools#25]

**Comment by ENE4546** [comment]
01-07 23:01:04 [DEBUG] nonebot | Checking for matchers in priority 1...
01-07 23:01:04 [DEBUG] nonebot | Checking for matchers in priority 5...
01-07 23:01:04 [DEBUG] nonebot | Checking for matchers in priority 10...
01-07 23:01:04 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-07 23:01:04 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_repeater)
01-07 23:01:04 [DEBUG] nonebot | Running handler Dependent(call=repeater)
01-07 23:01:04 [DEBUG] nonebot | Handler Dependent(call=repeater) skipped
01-07 23:01:04 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-07 23:01:04 [DEBUG] nonebot | Checking for matchers in priority 99...
01-07 23:01:04 [DEBUG] nonebot | Checking for matchers in priority 999...


如题，对Bot说：干员斯卡蒂 。没反应

**Comment by Mulsd** [comment]
看看cqhttp那边有没有发送内容？

**Comment by ENE4546** [comment]
> 看看cqhttp那边有没有发送内容？

除了我发给BOT的，没有内容了。
普通跟bot说话也是出现上面一样的报告

**Comment by Mulsd** [comment]
> 除了我发给BOT的，没有内容了。 普通跟bot说话也是出现上面一样的报告

你的bot可以收到来自cq的问题吗？
建议把日志级别改成 INFO ，获得更简明有效的日志试着私聊bot尝试触发指令，如果没有报错或者sent message之类的有可能是tx风控了

**Comment by Mulsd** [comment]
不对，日志里面怎么没有ak插件的内容？你截出来的都是复读🐔的？

**Comment by ENE4546** [comment]
> 不对，日志里面怎么没有ak插件的内容？你截出来的都是复读🐔的？

那应该都是复读机的

**Comment by ENE4546** [comment]
> > 除了我发给BOT的，没有内容了。 普通跟bot说话也是出现上面一样的报告
> 
> 你的bot可以收到来自cq的问题吗？ 建议把日志级别改成 INFO ，获得更简明有效的日志试着私聊bot尝试触发指令，如果没有报错或者sent message之类的有可能是tx风控了
只有方舟每日资源和活动可以用。其他的，什么塞壬音乐，公招都用不了
nonebot加载时出现  01-08 12:24:22 [ERROR] nonebot | Failed to import "nonebot_plugin_arktools"

**Comment by Mulsd** [comment]
日志截全一点，最后一行有原因的

**Comment by ENE4546** [comment]
> 日志截全一点，最后一行有原因的
C:\Users\ENE\Bot>nb run
01-08 12:32:02 [SUCCESS] nonebot | NoneBot is initializing...
Python-dotenv could not parse statement starting at line 14
01-08 12:32:02 [INFO] nonebot | Current Env: dev
01-08 12:32:02 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'987654321', '123456789'}, 'nickname': {'小小红', 'bot'}, 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'activities_data_path': 'C:\\Users\\ENE\\Downloads\\新活动的数据', 'custom_config1': 'config in env file', 'session_tokens:': None, 'operator_save_path': 'C:\\Users\\ENE\\Downloads\\干员信息查询生成', 'fastapi_reload': False, 'custom_config2': '# 留空则从系统环境变量读取，如不存在则为空字符串', 'activities_img_path': 'C:\\Users\\ENE\\Downloads\\新活动截图', 'chatgpt_refresh_interval': 15, 'repeater_min_message_times': 1, 'chatgpt_scope': 'public', 'chatgpt_command_prefix': '', 'chatgpt_need_at': 'False', 'chatgpt_token_path': 'config/chatgpt_token.yml', 'daily_levels_path': 'C:\\Users\\ENE\\Downloads\\每日资源关卡截图', 'recruitment_save_path': 'C:\\Users\\ENE\\Downloads\\公招查询结果', 'chatgpt_command': 'chat', 'chatgpt_image_render': 'False', 'repeater_min_message_length': 1, 'chatgpt_proxy': 'http://127.0.0.1:6512', 'repeater_group': ['780848374'], 'chatgpt_session_token': 'XXX', 'chatgpt_to_me': 'True'}
01-08 12:32:02 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
01-08 12:32:02 [ERROR] nonebot | Failed to import "nonebot_plugin_multi_chatgpt"
Traceback (most recent call last):
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run    run_bot(file, app)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ENE\Bot\.\bot.py", line 24, in <module>
    nonebot.load_plugin('nonebot_plugin_multi_chatgpt')
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_multi_chatgpt\__init__.py", line 7, in <module>
    from asyncChatGPT.asyncChatGPT import Chatbot
ModuleNotFoundError: No module named 'asyncChatGPT'
01-08 12:32:03 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_repeater"
01-08 12:32:03 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
01-08 12:32:03 [ERROR] nonebot | Failed to import "nonebot_plugin_apscheduler"
Traceback (most recent call last):
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run    run_bot(file, app)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\ENE\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ENE\Bot\.\bot.py", line 25, in <module>
    nonebot.load_from_toml("pyproject.toml")

**Comment by ENE4546** [comment]
error 有 
01-08 12:32:03 [ERROR] nonebot | Failed to import "nonebot_plugin_apscheduler"
RuntimeError: Module nonebot_plugin_apscheduler is not loaded as a plugin! Make sure not to import it before loading.
01-08 12:32:03 [ERROR] nonebot | Failed to import "nonebot_plugin_arktools"
RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!

**Comment by Mulsd** [comment]
删除 nonebot_plugin_apscheduler 插件再试一次

**Comment by ENE4546** [comment]
> 删除 nonebot_plugin_apscheduler 插件再试一次

删了，但还是有01-08 13:09:05 [ERROR] nonebot | Failed to import "nonebot_plugin_arktools"。。。

**Comment by Mulsd** [comment]
> > 删除 nonebot_plugin_apscheduler 插件再试一次
> 
> 删了，但还是有01-08 13:09:05 [ERROR] nonebot | Failed to import "nonebot_plugin_arktools"。。。

原因啊原因，每次报错的原因都是不同的
我推测可能是和某些插件冲突了
你先看看src目录里的插件有没有问题
再从bot.py中加载nonebot_plugin_apscheduler试试看

**Comment by ENE4546** [comment]
![image](https://user-images.githubusercontent.com/99572911/211198919-60d2d885-0935-4310-9602-7dc4fdb34774.png)
![image](https://user-images.githubusercontent.com/99572911/211198935-146de9b3-cb0f-42a4-a5cd-1c4855f42dcd.png)
src目录里没插件，也重新加载了orz

**Comment by NumberSir** [comment]
> _No description provided._

请重新下载最新版本
