### ISSUE TITLE
启动失败，已检查fastapi==0.88.0,最新版本也不行

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [NumberSir/nonebot_plugin_arktools#31]
import feedparser
没有写进[pyproject.toml](https://github.com/NCBM/nonebot-plugin-extrautils/blob/master/pyproject.toml)里面

**Comment by Umamusume-Agnes-Digital** [comment]
怪了，pip更新的时候，确实报错无法导入import feedparser没有找到模块，也发现没有安装

**Comment by Umamusume-Agnes-Digital** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/http11.py", line 112, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/asyncio.py", line 36, in read
    return b""
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_arktools/src/utils/update.py", line 260, in _init_game_files
    await ArknightsGameData(client).download_files()
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_arktools/src/utils/update.py", line 110, in download_files
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_arktools/src/utils/update.py", line 115, in save
    content = (await self._client.get(f"{url}/{file}", timeout=100)).content
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

02-19 03:28:54 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by NumberSir** [comment]
> Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions yield File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request resp = await self._pool.handle_async_request(req) File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request raise exc File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request response = await connection.handle_async_request(request) File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection.py", line 90, in handle_async_request return await self._connection.handle_async_request(request) File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/http11.py", line 112, in handle_async_request raise exc File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/http11.py", line 91, in handle_async_request ) = await self._receive_response_headers(**kwargs) File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers event = await self._receive_event(timeout=timeout) File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/http11.py", line 191, in _receive_event data = await self._network_stream.read( File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/asyncio.py", line 36, in read return b"" File "/usr/lib/python3.9/contextlib.py", line 137, in **exit** self.gen.throw(typ, value, traceback) File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions raise to_exc(exc) httpcore.ReadTimeout
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 671, in lifespan async with self.lifespan_context(app): File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in **aenter** await self._router.startup() File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 648, in startup await handler() File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_arktools/src/utils/update.py", line 260, in _init_game_files await ArknightsGameData(client).download_files() File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_arktools/src/utils/update.py", line 110, in download_files await asyncio.gather(*tasks) File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_arktools/src/utils/update.py", line 115, in save content = (await self._client.get(f"{url}/{file}", timeout=100)).content File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1757, in get return await self.request( File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1533, in request return await self.send(request, auth=auth, follow_redirects=follow_redirects) File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1620, in send response = await self._send_handling_auth( File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1648, in _send_handling_auth response = await self._send_handling_redirects( File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1685, in _send_handling_redirects response = await self._send_single_request(request) File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1722, in _send_single_request response = await transport.handle_async_request(request) File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request resp = await self._pool.handle_async_request(req) File "/usr/lib/python3.9/contextlib.py", line 137, in **exit** self.gen.throw(typ, value, traceback) File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions raise mapped_exc(message) from exc httpx.ReadTimeout
> 
> 02-19 03:28:54 [ERROR] uvicorn | Application startup failed. Exiting.

请更新插件
资源文件下载请求超时，请手动下载或更换镜像
