### ISSUE TITLE
公招报错，请问我应该怎么做

### ISSUE THREAD

**Issue by mskwi** [NumberSir/nonebot_plugin_arktools#32]
加载的时候就有如下报错：

02-19 16:20:22 [INFO] nonebot_plugin_arktools | ===== ARKNIGHTS-SQLITE CONNECTED.
02-19 16:20:22 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "D:\Project\qqbot\nonebot2\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once
    handle._run()
  File "C:\Program Files\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\internal\driver\driver.py", line 146, in _run_hook
    await asyncio.gather(*coros)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
    return await coro
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\src\utils\database.py", line 245, in _init_db
    await ArknightsDB.init_db()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\src\utils\database.py", line 49, in init_db
    await ArknightsDB.init_data()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\src\utils\database.py", line 61, in init_data
    await ArknightsDB._init_building_buff()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\src\utils\database.py", line 81, in _init_building_buff
    await asyncio.gather(*tasks)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\tortoise\models.py", line 1104, in update_or_create
    async with in_transaction(connection_name=db.connection_name) as connection:
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\tortoise\backends\base\client.py", line 255, in __aexit__
    await self.connection.commit()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\tortoise\backends\sqlite\client.py", line 195, in commit
    await self._connection.commit()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\aiosqlite\core.py", line 162, in commit
    await self._execute(self._conn.commit)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.ProgrammingError: Cannot operate on a closed database.
02-19 16:20:22 [INFO] nonebot_plugin_arktools | ##### ARKNIGHTS-SQLITE DATA ALL INITIATING ...
02-19 16:20:22 [INFO] nonebot_plugin_arktools |         - BuildingBuff data initiated.
02-19 16:20:22 [INFO] nonebot_plugin_arktools |         - WorkshopFormula data initiated.
02-19 16:20:24 [INFO] nonebot_plugin_arktools |         - Character data initiated.
02-19 16:20:24 [INFO] nonebot_plugin_arktools |         - Constance data initiated.
02-19 16:20:24 [INFO] nonebot_plugin_arktools |                 - RichTextStyle data initiated.
02-19 16:20:24 [INFO] nonebot_plugin_arktools |                 - TermDescription data initiated.
02-19 16:20:25 [INFO] nonebot_plugin_arktools |         - Equip data initiated
02-19 16:20:26 [INFO] nonebot_plugin_arktools |         - GachaPool data initiated
02-19 16:20:26 [INFO] nonebot_plugin_arktools |         - HandbookInfo data initiated.
02-19 16:20:27 [INFO] nonebot_plugin_arktools |         - Item data initiated
02-19 16:20:30 [INFO] nonebot_plugin_arktools |         - Skill data initiated
02-19 16:20:30 [INFO] nonebot_plugin_arktools | ===== ARKNIGHTS-SQLITE DATA ALL INITIATED

其他功能都好用的 公招识别tag后图片也跳不出来 报错如下

02-19 16:31:09 [INFO] nonebot_plugin_gocqhttp | [3253413664] 收到群 方舟(759625270) 内 柘(3031147044) 的消息: [CQ:reply,id=-533224594][CQ:at,qq=3031147044] /公招 (914318355)
02-19 16:31:09 [INFO] logging | 127.0.0.1:50430 - "GET /api/3253413664/process/status HTTP/1.1" 200
02-19 16:31:09 [SUCCESS] nonebot | OneBot V11 3253413664 | [message.group.normal]: Message 914318355 from 3031147044@[群:759625270] '[reply:id=-533224594][at:qq=3031147044] /公招'
02-19 16:31:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_arktools.src.tool_open_recruitment)
02-19 16:31:09 [INFO] nonebot_plugin_gocqhttp | [3253413664] 发送群 方舟(759625270) 的消息: [{"type":  ... (1098404997)
02-19 16:31:11 [INFO] nonebot_plugin_gocqhttp | [3253413664] 发送群 方舟(759625270) 的消息: [{"type":  ... (-663681729)
02-19 16:31:11 [INFO] logging | 127.0.0.1:50430 - "GET /api/accounts HTTP/1.1" 200
02-19 16:31:11 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_arktools.src.tool_open_recruitment) running complete
02-19 16:31:11 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_arktools.src.tool_open_recruitment) failed.
Traceback (most recent call last):
  File "D:\Project\qqbot\nonebot2\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once
    handle._run()
  File "C:\Program Files\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\src\tool_open_recruitment\__init__.py", line 71, in _
    image = draw.build_main()
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\src\tool_open_recruitment\data_source.py", line 136, in build_main
    self.result_images = [self.build_group(group) for group in self.result_groups]
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\src\tool_open_recruitment\data_source.py", line 136, in <listcomp>
    self.result_images = [self.build_group(group) for group in self.result_groups]
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\src\tool_open_recruitment\data_source.py", line 108, in build_group
    cht.avatar = cht.avatar.resize((128, 128))
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\src\core\models_v3.py", line 390, in avatar
    return self._avatar or Image.open(pcfg.arknights_gameimage_path / "avatar" / f"{self.id}.png")
  File "D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\PIL\Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Project\\qqbot\\nonebot2\\.venv\\Lib\\site-packages\\nonebot_plugin_arktools\\data\\arknights\\gameimage\\avatar\\char_253_greyy.png'

求佬帮帮看我应该怎么搞 谢谢！

**Comment by mskwi** [comment]
> 加载的时候就有如下报错：
> 
> 02-19 16:20:22 [INFO] nonebot_plugin_arktools | ===== ARKNIGHTS-SQLITE CONNECTED. 02-19 16:20:22 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled! Traceback (most recent call last): File "D:\Project\qqbot\nonebot2\bot.py", line 21, in nonebot.run() File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot__init__.py", line 273, in run get_driver().run(*args, **kwargs) File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run uvicorn.run( File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\uvicorn\main.py", line 569, in run server.run() File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\uvicorn\server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run return runner.run(main) File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete self.run_forever() File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever super().run_forever() File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 607, in run_forever self._run_once() File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once handle._run() File "C:\Program Files\Python311\Lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args)
> 
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\internal\driver\driver.py", line 146, in _run_hook
> > await asyncio.gather(*coros)
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
> > return await coro
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\dependencies__init__.py", line 108, in **call**
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot_plugin_arktools\src\utils\database.py", line 245, in _init_db
> > await ArknightsDB.init_db()
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot_plugin_arktools\src\utils\database.py", line 49, in init_db
> > await ArknightsDB.init_data()
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot_plugin_arktools\src\utils\database.py", line 61, in init_data
> > await ArknightsDB._init_building_buff()
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot_plugin_arktools\src\utils\database.py", line 81, in _init_building_buff
> > await asyncio.gather(*tasks)
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\tortoise\models.py", line 1104, in update_or_create
> > async with in_transaction(connection_name=db.connection_name) as connection:
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\tortoise\backends\base\client.py", line 255, in **aexit**
> > await self.connection.commit()
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\tortoise\backends\sqlite\client.py", line 195, in commit
> > await self._connection.commit()
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\aiosqlite\core.py", line 162, in commit
> > await self._execute(self._conn.commit)
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\aiosqlite\core.py", line 129, in _execute
> > return await future
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\aiosqlite\core.py", line 102, in run
> > result = function()
> > sqlite3.ProgrammingError: Cannot operate on a closed database.
> > 02-19 16:20:22 [INFO] nonebot_plugin_arktools | ##### ARKNIGHTS-SQLITE DATA ALL INITIATING ...
> > 02-19 16:20:22 [INFO] nonebot_plugin_arktools |         - BuildingBuff data initiated.
> > 02-19 16:20:22 [INFO] nonebot_plugin_arktools |         - WorkshopFormula data initiated.
> > 02-19 16:20:24 [INFO] nonebot_plugin_arktools |         - Character data initiated.
> > 02-19 16:20:24 [INFO] nonebot_plugin_arktools |         - Constance data initiated.
> > 02-19 16:20:24 [INFO] nonebot_plugin_arktools |                 - RichTextStyle data initiated.
> > 02-19 16:20:24 [INFO] nonebot_plugin_arktools |                 - TermDescription data initiated.
> > 02-19 16:20:25 [INFO] nonebot_plugin_arktools |         - Equip data initiated
> > 02-19 16:20:26 [INFO] nonebot_plugin_arktools |         - GachaPool data initiated
> > 02-19 16:20:26 [INFO] nonebot_plugin_arktools |         - HandbookInfo data initiated.
> > 02-19 16:20:27 [INFO] nonebot_plugin_arktools |         - Item data initiated
> > 02-19 16:20:30 [INFO] nonebot_plugin_arktools |         - Skill data initiated
> > 02-19 16:20:30 [INFO] nonebot_plugin_arktools | ===== ARKNIGHTS-SQLITE DATA ALL INITIATED
> 
> 其他功能都好用的 公招识别tag后图片也跳不出来 报错如下
> 
> 02-19 16:31:09 [INFO] nonebot_plugin_gocqhttp | [3253413664] 收到群 方舟(759625270) 内 柘(3031147044) 的消息: [CQ:reply,id=-533224594][CQ:at,qq=3031147044] /公招 (914318355) 02-19 16:31:09 [INFO] logging | 127.0.0.1:50430 - "GET /api/3253413664/process/status HTTP/1.1" 200 02-19 16:31:09 [SUCCESS] nonebot | OneBot V11 3253413664 | [message.group.normal]: Message 914318355 from 3031147044@[群:759625270] '[reply:id=-533224594][at:qq=3031147044] /公招' 02-19 16:31:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_arktools.src.tool_open_recruitment) 02-19 16:31:09 [INFO] nonebot_plugin_gocqhttp | [3253413664] 发送群 方舟(759625270) 的消息: [{"type": ... (1098404997) 02-19 16:31:11 [INFO] nonebot_plugin_gocqhttp | [3253413664] 发送群 方舟(759625270) 的消息: [{"type": ... (-663681729) 02-19 16:31:11 [INFO] logging | 127.0.0.1:50430 - "GET /api/accounts HTTP/1.1" 200 02-19 16:31:11 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_arktools.src.tool_open_recruitment) running complete 02-19 16:31:11 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_arktools.src.tool_open_recruitment) failed. Traceback (most recent call last): File "D:\Project\qqbot\nonebot2\bot.py", line 21, in nonebot.run() File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot__init__.py", line 273, in run get_driver().run(*args, **kwargs) File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run uvicorn.run( File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\uvicorn\main.py", line 569, in run server.run() File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\uvicorn\server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run return runner.run(main) File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete self.run_forever() File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever super().run_forever() File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 607, in run_forever self._run_once() File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once handle._run() File "C:\Program Files\Python311\Lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args) File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\message.py", line 141, in _check_matcher await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> 
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\message.py", line 187, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
> > await handler(
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot\dependencies__init__.py", line 108, in **call**
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot_plugin_arktools\src\tool_open_recruitment__init__.py", line 71, in _
> > image = draw.build_main()
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot_plugin_arktools\src\tool_open_recruitment\data_source.py", line 136, in build_main
> > self.result_images = [self.build_group(group) for group in self.result_groups]
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot_plugin_arktools\src\tool_open_recruitment\data_source.py", line 136, in 
> > self.result_images = [self.build_group(group) for group in self.result_groups]
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot_plugin_arktools\src\tool_open_recruitment\data_source.py", line 108, in build_group
> > cht.avatar = cht.avatar.resize((128, 128))
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\nonebot_plugin_arktools\src\core\models_v3.py", line 390, in avatar
> > return self._avatar or Image.open(pcfg.arknights_gameimage_path / "avatar" / f"{self.id}.png")
> > File "D:\Project\qqbot\nonebot2.venv\Lib\site-packages\PIL\Image.py", line 3227, in open
> > fp = builtins.open(filename, "rb")
> > FileNotFoundError: [Errno 2] No such file or directory: 'D:\Project\qqbot\nonebot2\.venv\Lib\site-packages\nonebot_plugin_arktools\data\arknights\gameimage\avatar\char_253_greyy.png'
> 
> 求佬帮帮看我应该怎么搞 谢谢！

没事了 我sql似乎没装
