### ISSUE TITLE
插件加载失败 TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Ra1n-qwq** [NumberSir/nonebot_plugin_arktools#4]
如题 操作系统 Centos7.6;Python 3.7.12 ;NoneBot2 v2.0.0-beta.4
报错信息如下：
```
07-09 01:38:20 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
07-09 01:38:20 [ERROR] nonebot | Failed to import "nonebot-plugin-arktools"
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.7/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 24, in <module>
    nonebot.load_plugin("nonebot-plugin-arktools")
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/nonebot_plugin_arktools-0.4.0-py3.7.egg/nonebot-plugin-arktools/__init__.py", line 3, in <module>
    from .open_recruitment import *
  File "/usr/local/lib/python3.7/site-packages/nonebot_plugin_arktools-0.4.0-py3.7.egg/nonebot-plugin-arktools/open_recruitment/__init__.py", line 6, in <module>
    from .data_source import get_recommend_tags
  File "/usr/local/lib/python3.7/site-packages/nonebot_plugin_arktools-0.4.0-py3.7.egg/nonebot-plugin-arktools/open_recruitment/data_source.py", line 12, in <module>
    async def get_recommend_tags(taglist: list[str]):
TypeError: 'type' object is not subscriptable
```
bot.py文件内容如下：
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import nonebot
from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter

# Custom your logger
# 
# from nonebot.log import logger, default_format
# logger.add("error.log",
#            rotation="00:00",
#            diagnose=False,
#            level="ERROR",
#            format=default_format)

# You can pass some keyword args config to init function
nonebot.init()
app = nonebot.get_asgi()

driver = nonebot.get_driver()
driver.register_adapter(ONEBOT_V11Adapter)

#nonebot.load_builtin_plugins("echo")
nonebot.load_plugin("nonebot-plugin-arktools")
nonebot.load_plugins("src/plugins/nonebot-plugin-petpet")
# Please DO NOT modify this file unless you know what you are doing!
# As an alternative, you should use command `nb` or modify `pyproject.toml` to load plugins
#nonebot.load_from_toml("pyproject.toml")

# Modify some config / config depends on loaded configs
# 
# config = driver.config
# do something...


if __name__ == "__main__":
    nonebot.logger.warning("Always use `nb run` to start the bot instead of manually running!")
    nonebot.run(app="__mp_main__:app")

```

**Comment by NumberSir** [comment]
已修复，请重新安装最新 0.4.1 版本的插件。
