### ISSUE TITLE
初始化数据库失败还要干员信息不出来

### ISSUE THREAD

**Issue by bilv123** [NumberSir/nonebot_plugin_arktools#40]
ERROR] nonebot_plugin_arktools | 初始化数据库失败：请检查是否与其它使用 Tortoise-ORM 的插件初始化冲突
04-07 03:31:59 [WARNING] nonebot_plugin_arktools | ***** ARKNIGHTS-SQLITE CONNECTING FAILED
4-07 03:36:29 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_arktools.src.tool_operator_info) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot_plugin_arktools\src\tool_operator_info\__init__.py", line 34, in _
    img_bytes = await BuildOperatorInfo(cht=cht).build_whole_image()
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot_plugin_arktools\src\tool_operator_info\data_source.py", line 46, in build_whole_image
    all_skills_img: Image = await self._build_all_skills()
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\nonebot_plugin_arktools\src\tool_operator_info\data_source.py", line 82, in _build_all_skills
    rank_icon = Image.open(gameimage_path / "ui" / "rank" / f"{lvl+1}.png").convert("RGBA").resize((96, 96))
  File "C:\Users\Administrator\Desktop\nonebot\genshin\.venv\lib\site-packages\PIL\Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\Administrator\\Desktop\\nonebot\\genshin\\data\\arktools\\arknights\\gameimage\\ui\\rank\\1.png'

**Comment by NumberSir** [comment]
> ERROR] nonebot_plugin_arktools | 初始化数据库失败：请检查是否与其它使用 Tortoise-ORM 的插件初始化冲突 04-07 03:31:59 [WARNING] nonebot_plugin_arktools | ***** ARKNIGHTS-SQLITE CONNECTING FAILED 4-07 03:36:29 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_arktools.src.tool_operator_info) failed. Traceback (most recent call last): File "", line 17, in File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot__init__.py", line 273, in run get_driver().run(*args, **kwargs) File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run uvicorn.run( File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\uvicorn\main.py", line 568, in run server.run() File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\uvicorn\server.py", line 59, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete self.run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever super().run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever self._run_once() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once handle._run() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args) File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> 
> > File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
> > await handler(
> > File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot\dependencies__init__.py", line 108, in **call**
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot_plugin_arktools\src\tool_operator_info__init__.py", line 34, in _
> > img_bytes = await BuildOperatorInfo(cht=cht).build_whole_image()
> > File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot_plugin_arktools\src\tool_operator_info\data_source.py", line 46, in build_whole_image
> > all_skills_img: Image = await self._build_all_skills()
> > File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\nonebot_plugin_arktools\src\tool_operator_info\data_source.py", line 82, in _build_all_skills
> > rank_icon = Image.open(gameimage_path / "ui" / "rank" / f"{lvl+1}.png").convert("RGBA").resize((96, 96))
> > File "C:\Users\Administrator\Desktop\nonebot\genshin.venv\lib\site-packages\PIL\Image.py", line 3283, in open
> > raise UnidentifiedImageError(msg)
> > PIL.UnidentifiedImageError: cannot identify image file 'C:\Users\Administrator\Desktop\nonebot\genshin\data\arktools\arknights\gameimage\ui\rank\1.png'

1. 检查是不是和其它用 `tortoise-orm` 的插件冲突了
2. 看看 `C:\Users\Administrator\Desktop\nonebot\genshin\data\arktools\arknights\gameimage\ui\rank\1.png` 有没有损坏。如果文件损坏就把 `data\arktools\arknights\gameimage` 文件夹删除后用 `更新方舟素材` 命令手动更新；或下载发行版中的 `data.zip` 压缩包解压到 `C:\Users\Administrator\Desktop\nonebot\genshin` 文件夹覆盖
3. 日志截全，比如启动过程加载了哪些插件、干员命令查的是谁、怎么复现，能截图就不要复制粘贴

**Comment by bilv123** [comment]
![image](https://user-images.githubusercontent.com/123937990/230531787-d3d25528-4f78-4530-87a0-ad95b90cf6f3.png)

**Comment by bilv123** [comment]
![image](https://user-images.githubusercontent.com/123937990/230532172-aff3b82a-fae0-4f34-b1a0-884fef0c6b1e.png)
![image](https://user-images.githubusercontent.com/123937990/230532203-5a161082-3f4a-4c5e-96e1-1d8854689968.png)

**Comment by NumberSir** [comment]
已更新出错的 `data` 文件夹，请重新下载
