### ISSUE TITLE
获取公告时遇到问题

### ISSUE THREAD

**Issue by Fui-Reconk** [NumberSir/nonebot_plugin_arktools#52]
10-31 15:28:23 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_arktools.src.tool_announce_push, lineno=19) failed.
Traceback (most recent call last):
  File "/root/Pallas-Bot/bot.py", line 36, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
  File "/root/Pallas-Bot/lib/python3.9/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/root/Pallas-Bot/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 821, in simple_run
    await handler(
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot_plugin_arktools/src/tool_announce_push/__init__.py", line 37, in _
    image = await html_to_pic(
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot_plugin_htmlrender/data_source.py", line 198, in html_to_pic
    img_raw = await page.screenshot(
  File "/root/Pallas-Bot/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 9974, in screenshot
    await self._impl_obj.screenshot(
  File "/root/Pallas-Bot/lib/python3.9/site-packages/playwright/_impl/_page.py", line 655, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "/root/Pallas-Bot/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/root/Pallas-Bot/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 490, in wrap_api_call
    return await cb()
  File "/root/Pallas-Bot/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================

**Comment by Fui-Reconk** [comment]
切换rss网站至本地镜像尝试过但无法解决
